In [1]:
import pandas as pd
from glycowork.motif.annotate import annotate_dataset, annotate_glycan

In [2]:
glycan_data = pd.read_csv("../../data/benchmark/glycans_glycowork.csv")
motif_data = pd.read_csv("../../data/benchmark/motifs_glycowork.csv")

# glycowork denotes an unknown modification position with O, for example GalOS.
assert not glycan_data["glycan"].str.contains("?S", regex=False).any()
assert not motif_data["motif"].str.contains("?S", regex=False).any()

In [3]:
glycans = glycan_data["glycan"]
glycans[:5]

0                                Glc(b1-3)Glc(b1-3)Glc
1                       Glc(b1-4)Glc(b1-4)Glc(b1-4)Glc
2                  Man(a1-3)[Man(a1-6)]Man(b1-4)GlcNAc
3    Fuc(a1-2)[GalNAc(a1-3)]Gal(b1-4)GlcNAc(b1-3)[N...
4                                      Gal(b1-3)GalNAc
Name: glycan, dtype: object

In [4]:
motifs = motif_data["motif"]
motifs[:5]

0                  Fuc(a1-2)Gal(b1-4)[Fuc(a1-3)]GlcNAc
1    Gal(b1-4)GlcNAc(b1-3)Gal(b1-4)GlcNAc(b1-3)Gal(...
2                                   GalNAc(b1-4)GlcNAc
3    Neu5Ac(a2-8)Neu5Ac(a2-8)Neu5Ac(a2-3)[GalNAc(b1...
4       Gal(a1-3)[Fuc(a1-2)]Gal(b1-3)[Fuc(a1-4)]GlcNAc
Name: motif, dtype: object

In [5]:
df = annotate_dataset(
    glycans,
    feature_set=["custom"],
    custom_motifs=motifs,
)

df

,Fuc(a1-2)Gal(b1-4)[Fuc(a1-3)]GlcNAc,Gal(b1-4)GlcNAc(b1-3)Gal(b1-4)GlcNAc(b1-3)Gal(b1-4)GlcNAc,GalNAc(b1-4)GlcNAc,Neu5Ac(a2-8)Neu5Ac(a2-8)Neu5Ac(a2-3)[GalNAc(b1-4)]Gal(b1-4)Glc,Gal(a1-3)[Fuc(a1-2)]Gal(b1-3)[Fuc(a1-4)]GlcNAc,GlcNAc(b1-3)[GalNAc(b1-4)]Gal(b1-4)Glc,Neu5Ac(a2-3)GalNAc(b1-3)Gal(b1-4)GlcNAc(b1-3)Gal(b1-4)Glc,Neu5Ac(a2-3)Gal(b1-4)[Fuc(a1-3)]GlcNAc,GalNAc(a1-3)[Fuc(a1-2)]Gal(b1-3)GalNAc,Gal(b1-3)GlcNAc(b1-3)Gal(b1-3)GlcNAc,...,IdoA(?1-?)GlcN2S,GlcN2S(?1-?)IdoA,Gal(a1-3)[Fuc(a1-2)]Gal(b1-3)GalNAc,Gal(a1-3)GalNAc,Fuc,Man,GlcNAc(b1-?)Man(a1-?)[GlcNAc(b1-?)Man(a1-?)]Man(b1-4)GlcNAc(b1-4)GlcNAc,GlcNAc(b1-?)[GlcNAc(b1-?)]Man(a1-?)[GlcNAc(b1-?)Man(a1-?)]Man(b1-4)GlcNAc(b1-4)GlcNAc,GlcNAc(b1-?)[GlcNAc(b1-?)]Man(a1-?)[GlcNAc(b1-?)[GlcNAc(b1-?)]Man(a1-?)]Man(b1-4)GlcNAc(b1-4)GlcNAc,Man(a1-3/6)Man(b1-4)GlcNAc(b1-4)GlcNAc
glycan,,,,,,,,,,,,,,,,,,,,,
Glc(b1-3)Glc(b1-3)Glc,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Glc(b1-4)Glc(b1-4)Glc(b1-4)Glc,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Man(a1-3)[Man(a1-6)]Man(b1-4)GlcNAc,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,3,0,0,0,0
Fuc(a1-2)[GalNAc(a1-3)]Gal(b1-4)GlcNAc(b1-3)[Neu5Gc(a2-6)]GalNAc,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
Gal(b1-3)GalNAc,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Neu5Ac(a2-3)Gal(b1-4)GlcNAc(b1-2)[Neu5Ac(a2-6)Gal(b1-4)GlcNAc(b1-6)]Man(a1-3)[Neu5Ac(a2-3)Gal(b1-4)GlcNAc(b1-2)[Neu5Ac(a2-3)Gal(b1-4)GlcNAc(b1-4)]Man(a1-6)]Man(b1-4)GlcNAc(b1-4)GlcNAc,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,3,4,4,1,2
Neu5Ac(a2-3)Gal(b1-4)GlcNAc(b1-2)Man(a1-3)[GlcNAc(b1-4)][Neu5Ac(a2-6)Gal(b1-4)GlcNAc(b1-2)Man(a1-6)]Man(b1-4)GlcNAc(b1-4)[Fuc(a1-6)]GlcNAc,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,3,1,0,0,2
GalNAc(b1-4)GlcNAc(b1-2)Man(a1-3)[Man(a1-3)[Man(a1-6)]Man(a1-6)]Man(b1-4)GlcNAc(b1-4)[Fuc(a1-6)]GlcNAc,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,5,0,0,0,2
Fuc(a1-2)Gal(b1-3)[Fuc(b1-4)]GlcNAc,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,0
Glc(a1-4)[Glc(a1-6)]Glc(a1-4)Glc,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
df.to_csv(
    "../../data/benchmark/glycowork_motif_annotations.csv",
    index=True,
    index_label="glycowork_glycan",
)

In [7]:
sulfate_wildcard_checks = pd.DataFrame(
    {
        "glycan": ["Gal3S", "Gal3/6S", "GalOS"],
        "motif": ["GalOS", "GalOS", "GalOS"],
    }
)
sulfate_wildcard_checks["matches"] = [
    annotate_dataset([glycan], custom_motifs=[motif], feature_set=["custom"]).iloc[0, 0]
    for glycan, motif in sulfate_wildcard_checks[["glycan", "motif"]].itertuples(index=False, name=None)
]
assert sulfate_wildcard_checks["matches"].eq(1).all()
sulfate_wildcard_checks

    glycan  motif  matches
0    Gal3S  GalOS        1
1  Gal3/6S  GalOS        1
2    GalOS  GalOS        1