In [10]:
import pandas as pd
from glycowork.motif.annotate import annotate_dataset, annotate_glycan

In [5]:
glycan_data = pd.read_csv("../../data/benchmark/glydb_data.csv")
motif_data = pd.read_csv("../../data/benchmark/glygen_motifs.csv")

In [21]:
glycans = glycan_data["glycan_structure"]
glycans = [g[:-4] for g in glycans]
glycans[:5]

['Glc(b1-3)Glc(b1-3)Glc',
 'Glc(b1-4)Glc(b1-4)Glc(b1-4)Glc',
 'Man(a1-3)[Man(a1-6)]Man(b1-4)GlcNAc',
 'Fuc(a1-2)[GalNAc(a1-3)]Gal(b1-4)GlcNAc(b1-3)[Neu5Gc(a2-6)]GalNAc',
 'Gal(b1-3)GalNAc']

In [22]:
motif_data

     accession  ... graph
0           45  ...   NaN
1            4  ...   NaN
2           16  ...   NaN
3          109  ...   NaN
4           46  ...   NaN
..         ...  ...   ...
178       1037  ...   NaN
179       1038  ...   NaN
180       1039  ...   NaN
181       1040  ...   NaN
182       1041  ...   NaN

[183 rows x 6 columns]

In [28]:
not_whole_motif_data = motif_data[motif_data["alignment"] != "whole"]
motifs = not_whole_motif_data["iupac"]
motifs = [m[:-4] for m in motifs]
terminals = not_whole_motif_data["alignment"]
terminals = terminals.replace({"substructure": "flexible", "core": "internal"})

In [31]:
df = annotate_dataset(
    glycans,
    feature_set=["custom"],
    custom_motifs=motifs,
    termini_list=terminals.tolist()
)

df

                                                    Fuc(a1-2)Gal(b1-4)[Fuc(a1-3)]GlcNAc  ...  Man(a1-3/6)Man(b1-4)GlcNAc(b1-4)GlcNAc
Glc(b1-3)Glc(b1-3)Glc                                                                 0  ...                                       0
Glc(b1-4)Glc(b1-4)Glc(b1-4)Glc                                                        0  ...                                       0
Man(a1-3)[Man(a1-6)]Man(b1-4)GlcNAc                                                   0  ...                                       0
Fuc(a1-2)[GalNAc(a1-3)]Gal(b1-4)GlcNAc(b1-3)[Ne...                                    0  ...                                       0
Gal(b1-3)GalNAc                                                                       0  ...                                       0
...                                                                                 ...  ...                                     ...
GalNAc(b1-4)GlcNAc(b1-2)Man(a1-3)[Man(a1-3)[Man...                                    0  ...                                       2
Glc(a1-4)Glc(a1-4)Glc(a1-4)Glc(a1-4)Glc(a1-4)Gl...                                    0  ...                                       0
Fuc(a1-2)Gal(b1-3)[Fuc(b1-4)]GlcNAc                                                   0  ...                                       0
Glc(a1-3)Glc(a1-4)Glc(a1-3)Glc                                                        0  ...                                       0
Glc(a1-4)[Glc(a1-6)]Glc(a1-4)Glc                                                      0  ...                                       0

[7074 rows x 108 columns]

In [33]:
df.to_csv("../../data/benchmark/glycowork_motif_annotations.csv", index=True)